# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Dasmaeh"
license = "MIT"
licenselink = "https://github.com/dasmaeh/hugo-theme-dasmaeh/blob/master/LICENSE"
description = "My personal theme for gohugo. Still very much work in progress."
homepage = "https://github.com/dasmaeh/hugo-theme-dasmaeh"
tags = ["blog"]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "Jan Köster (dasmaeh)"
  homepage = "https://dasmaeh.de"
